
# This file is automatically generated, you probably don't want to edit this

correlationOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "correlationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            corrvars = NULL,
            ctrlvars = NULL,
            personCoef = TRUE,
            spearmanCoef = FALSE,
            partialCoef = FALSE,
            TetrachoricCoef = FALSE,
            PolychoricCoef = FALSE,
            BiserialCoef = FALSE,
            sidSig = "twotailed",
            GaussianPlot = FALSE,
            shwSig = TRUE,
            flgSig = TRUE, ...) {

            super$initialize(
                package='Correlations',
                name='correlation',
                requiresData=TRUE,
                ...)

            private$..corrvars <- jmvcore::OptionVariables$new(
                "corrvars",
                corrvars,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..ctrlvars <- jmvcore::OptionVariables$new(
                "ctrlvars",
                ctrlvars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..personCoef <- jmvcore::OptionBool$new(
                "personCoef",
                personCoef,
                default=TRUE)
            private$..spearmanCoef <- jmvcore::OptionBool$new(
                "spearmanCoef",
                spearmanCoef,
                default=FALSE)
            private$..partialCoef <- jmvcore::OptionBool$new(
                "partialCoef",
                partialCoef,
                default=FALSE)
            private$..TetrachoricCoef <- jmvcore::OptionBool$new(
                "TetrachoricCoef",
                TetrachoricCoef,
                default=FALSE)
            private$..PolychoricCoef <- jmvcore::OptionBool$new(
                "PolychoricCoef",
                PolychoricCoef,
                default=FALSE)
            private$..BiserialCoef <- jmvcore::OptionBool$new(
                "BiserialCoef",
                BiserialCoef,
                default=FALSE)
            private$..sidSig <- jmvcore::OptionList$new(
                "sidSig",
                sidSig,
                options=list(
                    "onetailed",
                    "twotailed"),
                default="twotailed")
            private$..GaussianPlot <- jmvcore::OptionBool$new(
                "GaussianPlot",
                GaussianPlot,
                default=FALSE)
            private$..shwSig <- jmvcore::OptionBool$new(
                "shwSig",
                shwSig,
                default=TRUE)
            private$..flgSig <- jmvcore::OptionBool$new(
                "flgSig",
                flgSig,
                default=TRUE)

            self$.addOption(private$..corrvars)
            self$.addOption(private$..ctrlvars)
            self$.addOption(private$..personCoef)
            self$.addOption(private$..spearmanCoef)
            self$.addOption(private$..partialCoef)
            self$.addOption(private$..TetrachoricCoef)
            self$.addOption(private$..PolychoricCoef)
            self$.addOption(private$..BiserialCoef)
            self$.addOption(private$..sidSig)
            self$.addOption(private$..GaussianPlot)
            self$.addOption(private$..shwSig)
            self$.addOption(private$..flgSig)
        }),
    active = list(
        corrvars = function() private$..corrvars$value,
        ctrlvars = function() private$..ctrlvars$value,
        personCoef = function() private$..personCoef$value,
        spearmanCoef = function() private$..spearmanCoef$value,
        partialCoef = function() private$..partialCoef$value,
        TetrachoricCoef = function() private$..TetrachoricCoef$value,
        PolychoricCoef = function() private$..PolychoricCoef$value,
        BiserialCoef = function() private$..BiserialCoef$value,
        sidSig = function() private$..sidSig$value,
        GaussianPlot = function() private$..GaussianPlot$value,
        shwSig = function() private$..shwSig$value,
        flgSig = function() private$..flgSig$value),
    private = list(
        ..corrvars = NA,
        ..ctrlvars = NA,
        ..personCoef = NA,
        ..spearmanCoef = NA,
        ..partialCoef = NA,
        ..TetrachoricCoef = NA,
        ..PolychoricCoef = NA,
        ..BiserialCoef = NA,
        ..sidSig = NA,
        ..GaussianPlot = NA,
        ..shwSig = NA,
        ..flgSig = NA)
)

correlationResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        text1 = function() private$.items[["text1"]],
        text2 = function() private$.items[["text2"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlation")
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="To Do"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text1",
                title="Pearson Correlation"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="Spearman Correlation"))}))

correlationBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "correlationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'Correlations',
                name = 'correlation',
                version = c(1,0,0),
                options = options,
                results = correlationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Correlation
#'
#' 
#' @param data The data as a data frame.
#' @param corrvars .
#' @param ctrlvars .
#' @param personCoef \code{TRUE} (default) or \code{FALSE}, provide Pearson
#' @param spearmanCoef \code{TRUE} (default) or \code{FALSE}, provide Spearman
#' @param partialCoef \code{TRUE} (default) or \code{FALSE}, provide Partial
#' @param TetrachoricCoef \code{TRUE} (default) or \code{FALSE}, provide
#'   Tetrachoric
#' @param PolychoricCoef \code{TRUE} (default) or \code{FALSE}, provide
#'   Polychoric
#' @param BiserialCoef \code{TRUE} (default) or \code{FALSE}, provide Biserial
#' @param sidSig .
#' @param GaussianPlot \code{TRUE} (default) or \code{FALSE}, provide
#'   correlation plot
#' @param shwSig .
#' @param flgSig .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
correlation <- function(
    data,
    corrvars,
    ctrlvars,
    personCoef = TRUE,
    spearmanCoef = FALSE,
    partialCoef = FALSE,
    TetrachoricCoef = FALSE,
    PolychoricCoef = FALSE,
    BiserialCoef = FALSE,
    sidSig = "twotailed",
    GaussianPlot = FALSE,
    shwSig = TRUE,
    flgSig = TRUE) {

    if ( ! requireNamespace('jmvcore'))
        stop('correlation requires jmvcore to be installed (restart may be required)')

    if ( ! missing(corrvars)) corrvars <- jmvcore::resolveQuo(jmvcore::enquo(corrvars))
    if ( ! missing(ctrlvars)) ctrlvars <- jmvcore::resolveQuo(jmvcore::enquo(ctrlvars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(corrvars), corrvars, NULL),
            `if`( ! missing(ctrlvars), ctrlvars, NULL))


    options <- correlationOptions$new(
        corrvars = corrvars,
        ctrlvars = ctrlvars,
        personCoef = personCoef,
        spearmanCoef = spearmanCoef,
        partialCoef = partialCoef,
        TetrachoricCoef = TetrachoricCoef,
        PolychoricCoef = PolychoricCoef,
        BiserialCoef = BiserialCoef,
        sidSig = sidSig,
        GaussianPlot = GaussianPlot,
        shwSig = shwSig,
        flgSig = flgSig)

    analysis <- correlationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
